import type { Metadata } from "next";
import { Geist, Geist_Mono, Megrim, Urbanist } from "next/font/google";
import "./globals.css";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const urbanist = Urbanist({
  variable: "--font-urbanist-sans",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const megrim = Megrim({
  subsets: ['latin'],
  variable: '--font-megrim-sans',
  display: 'swap',
  weight: '400',
  style: 'normal',
  preload: true,
  fallback: ['sans-serif'],
  adjustFontFallback: true,
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${geistMono.variable} ${megrim.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
